/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IOrderRegistry__factory } from "./IOrderRegistry__factory";
export { ShipmentRegistry__factory } from "./ShipmentRegistry__factory";
