/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IOrderRegistry } from "./IOrderRegistry";
export type { ShipmentRegistry } from "./ShipmentRegistry";
